### ISSUE TITLE
Operator PodMonitor

### ISSUE THREAD

**Issue by itay-grudev** [cloudnative-pg/charts#107]
Can a PodMonitor be added to the chart based on the example in the [documentation](https://cloudnative-pg.io/documentation/current/monitoring/#monitoring-the-operator)?

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cnpg-controller-manager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudnative-pg
  podMetricsEndpoints:
    - port: metrics
```
