### ISSUE TITLE
helm chart does not support recently-added region to s3credentials

### ISSUE THREAD

**Issue by ahgraber** [cloudnative-pg/charts#14]
ref: https://github.com/cloudnative-pg/cloudnative-pg/pull/207 

cluster spec (truncated):
```yaml
  backup:
    barmanObjectStore:
      destinationPath: "s3://BUCKET
      endpointURL: "S3_ENDPOINT"
      s3Credentials:
        accessKeyId:
          name: s3-secret
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: s3-secret
          key: ACCESS_SECRET_KEY
        # region: us-east
```

`Error: [...] .spec.backup.barmanObjectStore.s3Credentials.region: field not declared in schema`

I have deployed the operator via helm chart, version 0.13.1
