### ISSUE TITLE
podSecurityContext expose supplementalGroups

### ISSUE THREAD

**Issue by mauza** [cloudnative-pg/charts#161]
As part of security the cluster I'm trying to deploy requires that pod security includes `supplementalGroups: - 1`

```
  podSecurityContext:
    fsGroup: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    runAsUser: 1001
    supplementalGroups:
      - 1
    seccompProfile:
      type: RuntimeDefault
```
I'm hoping that we can plumb that through to the values.yaml. I'm pretty sure that would need to be included in the CRDs especially for the `Cluster` resource.
