### ISSUE TITLE
Add nodeSelector and tolerations to cluster chart for storage nodes

### ISSUE THREAD

**Issue by Jamison1** [cloudnative-pg/charts#187]
When deploying to an automated k8s cluster with separate storage nodes, the pg cluster needs to utilize either nodeAffinity or nodeSelector to ensure placement on storage nodes.  NodeSelector is preferred.

Additionally, for the taints on the storage nodes the cluster needs tolerations with key, operator, value & effect fields.

Example for values.yaml file:
```
# -- Nodeselector for the cluster to be installed.
nodeSelector:
  node-role.kubernetes.io/storage: storage

# -- Tolerations for the cluster to be installed.
tolerations:
  - key: "storage"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
```
This could be added to the cluster chart values file before the affinity rules to keep uniformity with the operator chart values file.

It would also need to be added to the cluster.yaml file before affinity

Example for templates cluster.yaml file:
```
{{- with .Values.cluster.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.cluster.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.cluster.affinity }} # Add before affinity
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
```

**Comment by itay-grudev** [comment]
While this can be done, it's not really compatible with how the operator works. Instead the whole affinity section is mapped to [`ClusterSpec.AffinityConfiguration`](https://cloudnative-pg.io/documentation/current/cloudnative-pg.v1/#postgresql-cnpg-io-v1-AffinityConfiguration) allowing you to set all of those properties through `cluster.affinity` in the chart.

**Comment by Jamison1** [comment]
Ok, thanks I have that working for cluster.  What about the pooler section?  What would be the format for that?  When I try pooler.template.spec.affinity.tolerations I get an error about tolerations not recognized.

**Comment by itay-grudev** [comment]
@Jamison1 Looking up the API specs [here](https://cloudnative-pg.io/documentation/current/cloudnative-pg.v1/#postgresql-cnpg-io-v1-PodTemplateSpec) and [here](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#podspec-v1-core), I think you should try:

```
pooler.template.spec.tolerations
```

**Comment by Jamison1** [comment]
Getting an error with pooler.template.spec when trying with the following:

```
pooler:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/type
                operator: In
                values:
                - type
      tolerations:
      - key: "type"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

```

It looks like that is for spec.container settings based on the error message:

`Error: Pooler.postgresql.cnpg.io \"cnpg-cluster-pooler-rw\" is invalid: spec.template.spec.containers: Required value`

Can affinity be added to pooler? such as  `pooler.affinity`
