### ISSUE TITLE
Add support for additional labels in PodMonitor

### ISSUE THREAD

**Issue by cvrajeesh** [cloudnative-pg/charts#195]
Currently, there is no way to add extra labels for `PodMonitor`. This is useful when they're discovered using specific labels e.g. `kube-prometheus-stack` expects a label `release: kube-prometheus-stack` on the PodMonitor.

Suggestions

1. New key called `podMonitorAdditionalLabels`

```yaml
monitoring:
  podMonitorEnabled: true
  podMonitorAdditionalLabels:
    release: kube-prometheus-stack
```

2. Dreprecate `podMonitorEnabled` instead and create a new key called `podMonitor`

```yaml
monitoring:
  podMonitor:
    enabled: true
    additionalLabels:
       release: kube-prometheus-stack
```

This needs to be done for both `cloudnative-pg` and `cluster` charts

**Comment by cvrajeesh** [comment]
Can't do this on the `cluster` charts, unless this is fixed https://github.com/cloudnative-pg/cloudnative-pg/discussions/1617

**Comment by itay-grudev** [comment]
@cvrajeesh I've bypassed this issue by setting the following in my `kube-prometheus-stack` installation so that it no longer looks for a release label:

```yaml
prometheus:
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
```

That being said, if this is still an issue in the operator we should raise a ticket from the https://github.com/cloudnative-pg/cloudnative-pg/discussions/1617 discussion that the `Cluster` labels are not replicated to the `PodMonitor`.

**Comment by itay-grudev** [comment]
P.S. We already renamed the values for the monitoring section:
```yaml
cluster:
  monitoring:
    enabled: false
    podMonitor:
      enabled: true
```
