### ISSUE TITLE
Add support for pgpooler to use private image registry

### ISSUE THREAD

**Issue by tgumleo** [cloudnative-pg/charts#204]
Requirement to point pooler to private registry for images - currently have to stand this up outside of the Helm chart so would be handy to include this.

To support, need to map helm to:
```
spec:
  template:
      spec:
         containers:
             - name: pgbouncer
               image: private-image-path

```
