### ISSUE TITLE
cluster.annotations does not annotate pods 

### ISSUE THREAD

**Issue by fakeNews-jpg** [cloudnative-pg/charts#235]
Add annotations to cluster like this : 

```
cluster:
  annotations:
    exampleannotation: "exampleannotation"
  enableSuperuserAccess: true
  initdb:
    database: "my_app_db"
    owner: "coucou"
    secret:
      name: "pg-app-user"
  superuserSecret: 'pg-superuser'
type: postgresql
```

No annotations are added to our cluster pods, 

Is it the expected behavior? If yes how do we add annotations to our pods? 

Thanks a lot in advance, 

F.N.
