### ISSUE TITLE
`object_store` recovery is not possible without `clusterName` set

### ISSUE THREAD

**Issue by mrclrchtr** [cloudnative-pg/charts#243]
Version 0.0.6 of Cluster-Chart

The following full config is not possible without `clusterName` set:
```
backups:
  enabled: true
  data:
    encryption: "" # Contabo does not support encryption
  wal:
    encryption: "" # Contabo does not support encryption
  endpointURL: "https://eu2.contabostorage.com"
  s3:
    bucket: "cnpg-cluster"
    accessKey: "xxx"
    secretKey: "xxx"
    path: "/backups"
  scheduledBackups:
    - name: daily-backup
      schedule: "0 * * * * *" # Daily at midnight
      backupOwnerReference: self

mode: recovery
recovery:
  method: "object_store"
  endpointURL: "https://eu2.contabostorage.com"
  # clusterName: "cnpg-cluster"
  s3:
    bucket: "cnpg-cluster"
    accessKey: "xxx"
    secretKey: "xxx"
    path: "/recovery"
```

With cluster name, the recovery works perfectly.

I did not use a different cluster name for the backup.
It's the same config, I want to recover from.

**Comment by itay-grudev** [comment]
Is your Helm release called the same?

**Comment by mrclrchtr** [comment]
I'm using kustomize:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cnpg-cluster
    repo: https://cloudnative-pg.github.io/charts
    releaseName: cnpg-cluster
    version: 0.0.7
    valuesFile: ../../../base/cnpg-cluster/values.yaml
```

So the it's the same I assume.
