### ISSUE TITLE
Unable to upgrade to cloudnative-pg chart `v0.21.0` due to grafana dashboard being enabled

### ISSUE THREAD

**Issue by onedr0p** [cloudnative-pg/charts#267]
I had to disable the grafana dashboard option or else I would get this error:

```
  Warning  UpgradeFailed     4s (x3 over 10s)  helm-controller  (combined from similar events): Helm upgrade failed for release database/cloudnative-pg with chart cloudnative-pg@0.21.0: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
  line 9: mapping key "grafana_dashboard" already defined at line 8
```

helm values:

```yaml
    crds:
      create: true
    monitoring:
      podMonitorEnabled: false
      grafanaDashboard:
        create: true
```
