### ISSUE TITLE
Can't get monitoring working

### ISSUE THREAD

**Issue by amalic** [cloudnative-pg/charts#279]
I can't get monitoring working. What am I missing?

I have installed Prometheus and Grafana via [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack).
```shell
helm repo add prometheus-community  https://prometheus-community.github.io/helm-charts
helm upgrade \
  --install kube-prometheus-stack prometheus-community/kube-prometheus-stack \
  --namespace observability \
  --create-namespace \
  --wait
``` 

After that I have added CPNG operator
```shell
helm repo add cnpg  https://cloudnative-pg.github.io/charts
helm upgrade \
  --install cnpg cnpg/cloudnative-pg \
  --namespace cpng \
  --create-namespace \
  --set monitoring.podMonitorEnabled=true \
  --wait
```

And applied following manifest to deploy a cluster
```
---
apiVersion: v1
kind: Secret
metadata:
  name: testapp-db-secret
type: kubernetes.io/basic-auth
data:
  username: dGVzdGFwcA== # testapp
  password: dGVzdGFwcF9wd2Q= # testapp_pwd
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster
spec:
  instances: 3 # 9 seems to be the max value here
  bootstrap:
    initdb:
      database: "testapp_db"
      owner: "testapp"
      secret:
        name: testapp-db-secret
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
  walStorage:
    size: 1Gi
    storageClass: gp2
  monitoring:
    enablePodMonitor: true
  affinity:
    enablePodAntiAffinity: true # true (derault)
    topologyKey: kubernetes.io/hostname # kubernetes.io/hostname
    podAntiAffinityType: preferred #preferred (default), required
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pg-pooler-rw
spec:
  cluster:
    name: pg-cluster
  instances: 1
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
  template:
    metadata:
      labels:
        app: pooler
    spec:
      containers: []
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - pooler
              topologyKey: "kubernetes.io/hostname"
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: pg-cluster-monitor
spec:
  selector:
    matchLabels:
      postgresql: pg-cluster
  podMetricsEndpoints:
  - port: metrics
```

**Comment by amalic** [comment]
Fond the solution here -> https://github.com/prometheus-operator/prometheus-operator/issues/3636#issuecomment-796688902

```shell
helm upgrade \
  --install kube-prometheus-stack prometheus-community/kube-prometheus-stack \
  --namespace o11y-system \
  --create-namespace \
  --set prometheus.prometheusSpec.podMonitorSelectorNilUsesHelmValues=false \
  --wait
```

**Comment by itay-grudev** [comment]
In general I would suggest the following configuration to avoid these issues:

```
prometheus:
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
```
