### ISSUE TITLE
[Help] PgBouncer NodeSelector

### ISSUE THREAD

**Issue by clickersmudge** [cloudnative-pg/charts#285]
Hi,
I can't figure out how to configure PgBouncer to schedule on the  the indicated node.

How to properly set the
```
# nodeSelector:
      # example: example
```

for Pgbouncer in Helm Chart?

**Comment by itay-grudev** [comment]
The Pooler deployment is managed by the operator, but you can pass in a `template` to override certain properties.

See [`pooler.template`](https://github.com/cloudnative-pg/charts/blob/c664085cee5355596b4b18ebfceb71ec1a48fba1/charts/cluster/values.yaml#L299).

https://cloudnative-pg.io/documentation/1.23/cloudnative-pg.v1/#postgresql-cnpg-io-v1-PoolerSpec

**Comment by clickersmudge** [comment]
Thans @itay-grudev

**Comment by clickersmudge** [comment]
Hi @itay-grudev 

I'm trying

```
template:
  nodeSelector:
    architecture: x86
```

```
template:
    spec:
      containers:
        nodeSelector:
          architecture: x86
```

And some other combinations, but it doesn't work.

**Comment by itay-grudev** [comment]
If you follow the API documentation:
- https://cloudnative-pg.io/documentation/1.23/cloudnative-pg.v1/#postgresql-cnpg-io-v1-PoolerSpec
- https://cloudnative-pg.io/documentation/1.23/cloudnative-pg.v1/#postgresql-cnpg-io-v1-PodTemplateSpec
- https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#podspec-v1-core

You will find, the correct configuration to be:

```yaml
pooler:
  template:
    spec:
      nodeSelector:
        architecture: x86
```
