### ISSUE TITLE
ScheduledBackup "schedule" paremeter fails with some values

### ISSUE THREAD

**Issue by walterbaidal** [cloudnative-pg/charts#288]
Hi,

When trying this configuration because of high RPO requirements:

```yaml    
  scheduledBackups:
    - name: every-four-hours-backup
      schedule: "* */4 * * *"
      backupOwnerReference: self
```

I get this error when helm installing:

> Error: UPGRADE FAILED: YAML parse error on postgres-cluster/charts/cluster/templates/scheduled-backups.yaml: error converting YAML to JSON: yaml: line 13: did not find expected alphabetic or numeric character

A workaround to fix this problem I have already experienced in the past is adding extra single quotes in the schedule parameter:

```yaml    
  scheduledBackups:
    - name: every-four-hours-backup
      schedule: '"* */4 * * *"'
      backupOwnerReference: self
```

But to fully solve this issue, a change in the template is required. I will open a PR after creating this issue.
