### ISSUE TITLE
Setting up pg_hba not working

### ISSUE THREAD

**Issue by ilbarone87** [cloudnative-pg/charts#308]
Hello everyone,
I'm trying to set pg_hba conf but the helm values don't seem to work.
What I've tried so far is:

```
...
  postgresql:
    parameters:
      shared_buffers: 256MB
      pg_stat_statements.max: '10000'
      pg_stat_statements.track: all
      auto_explain.log_min_duration: '10s'
    pg_hba: "host all all all password"
```

or 

```
  postgresql:
      shared_buffers: 256MB
      pg_stat_statements.max: '10000'
      pg_stat_statements.track: all
      auto_explain.log_min_duration: '10s'
      pg_hba: "host all all all password"
```

But i'm getting this error:

`LOG:  unrecognized configuration parameter "pg_hba" in file "/var/lib/postgresql/data/pgdata/custom.conf" line 20"`
