### ISSUE TITLE
gkeEnvironment conflict?

### ISSUE THREAD

**Issue by rocket357** [cloudnative-pg/charts#311]
https://github.com/cloudnative-pg/charts/blob/b378ad06aee0e9902eaaf8413784e5e3bb724861/charts/cluster/templates/_barman_object_store.tpl#L64-L67

I'm setting up a test environment in gke, and I've set the following in values:

```
backups:
  enabled: true
  provider: google
  google:
    gkeEnvironment: true
    bucket: my-test-bucket
    path: my-test-path
```

Via the linked template above, I see the following:

```
        googleCredentials:
        gkeEnvironment: false
        applicationCredentials:
          name: cnpg-database-cluster-backup-google-creds
          key: APPLICATION_CREDENTIALS
```

With this configuration, I'm seeing the following in helm output:

```
COMBINED OUTPUT:
  Error: UPGRADE FAILED: release cloudnative-pg-database-cluster failed, and has been rolled back due to atomic being set: cannot patch "cloudnative-pg-database-cluster" with kind Cluster: admission webhook "vcluster.cnpg.io" denied the request: Cluster.cluster.cnpg.io "cloudnative-pg-database-cluster" is invalid: spec.backupConfiguration.googleCredentials: Invalid value: v1.GoogleCredentials{ApplicationCredentials:(*v1.SecretKeySelector)(0xc001e0ada0), GKEEnvironment:true}: if gkeEnvironment is true, secret with credentials must not be provided
```

So it looks like the [docs](https://cloudnative-pg.io/documentation/1.18/api_reference/#googlecredentials) are not entirely accurate (specifically: "GoogleCredentials is the type for the Google Cloud Storage credentials. This needs to be specified even if we run inside a GKE environment.")

The operator I'm running is cloudnative-pg latest (0.21.4).  Is there additional configuration I've overlooked?
