### ISSUE TITLE
[BUG] cluster chart uses incorrect type for initdb secret

### ISSUE THREAD

**Issue by nilfr** [cloudnative-pg/charts#361]
Hi,

when using the default values as a template for the deployment of a new cluster, I have noticed that the secret reference in `cluster.initdb.secret` should contain a `LocalReference`, which is an object with the `name` key, rather than just a string.

The problematic section contains:
```yaml
cluster:
  ...
  initdb: {}
    ...
    # This should be a `LocalReference` instead.
    # secret: "" # Name of the secret containing the initial credentials for the owner of the user database. If empty a new secret will be created from scratch
...
```

> **Note:** I will submit a PR for this shortly.
