### ISSUE TITLE
PostgresConfiguration.spec.postgresql.parameters 

### ISSUE THREAD

**Issue by ondrej337** [cloudnative-pg/charts#388]
Hi,
I've just tried to deploy default:  values.yaml file and it seems doesn't work:
helm upgrade --install database \
--namespace cloudnative-pg \
--create-namespace \
--values values.yaml \
cnpg/cluster

Release "database" does not exist. Installing it now.
Error: 1 error occurred:
        * admission webhook "mcluster.cnpg.io" denied the request: json: cannot unmarshal object into Go struct field PostgresConfiguration.spec.postgresql.parameters of type string
        
Can you please have a look?
Thank you

**Comment by ppfenning92** [comment]
I have a similar issue. Could you provide the chart version and also the relevant parts from your values.yaml please?
I'm trying to fix the issue

**Comment by MoonMoon2** [comment]
In was able to fix it by changing the order of the keywords in the chart. Submitted a pull request with the fix as well.

In the templates/cluster.yaml file move postgresql.parameters to be below pg_hba and pg_indent on lines 63-68 as below

```yaml
    pg_hba:
      {{- toYaml .pg_hba | nindent 6 }}
    pg_ident:
      {{- toYaml .pg_ident | nindent 6 }}
    parameters:
      {{- toYaml .parameters | nindent 6 }}
```
