### ISSUE TITLE
Setting maintenance_work_mem does not apply to server

### ISSUE THREAD

**Issue by orlovmyk** [cloudnative-pg/charts#394]
According to CNPG guide, I've tried to set `maintenance_work_mem` as well as other params in my cluster:
```
    postgresql:
      parameters:
        shared_buffers: "2GB"
        effective_cache_size: "6GB"
        work_mem: "64MB"
        random_page_cost: "4" # default
        maintenance_work_mem: "64MB"
  ```
  
 
Other params works fine, but `maintenance_work_mem` remains default. Also I've check guide it's not fixed param:
https://cloudnative-pg.io/documentation/1.16/postgresql_conf/#fixed-parameters

<img width="1701" alt="image" src="https://github.com/user-attachments/assets/7af7f18a-d6f4-4e3f-bad1-70bfa66aee3c">
<img width="1716" alt="image" src="https://github.com/user-attachments/assets/61f58b62-9b8d-48b4-a925-8e7c7dc4d9e7">
