### ISSUE TITLE
Chart cnpg/cluster duplicate key cluster.postgresql.parameters.

### ISSUE THREAD

**Issue by marcossilvestrini** [cloudnative-pg/charts#408]
I'm trying to add the max_connections parameter but it's getting doubled.

values.yaml:

```
fullnameOverride: "test-cluster"
type: postgresql
mode: standalone
cluster:
  storage:
    size: 10Gi
    storageClass: ""
  walStorage:
    enabled: false
    size: 2Gi
    storageClass: ""
  priorityClassName: ""
  primaryUpdateMethod: switchover
  primaryUpdateStrategy: unsupervised
  logLevel: "info"
  enableSuperuserAccess: true
  superuserSecret: ""
  postgresql:
    # -- PostgreSQL configuration options (postgresql.conf)
    parameters:
      max_connections: 300
```

Helm templat result:

```
  postgresql:
    shared_preload_libraries:
    parameters:
      parameters:
        max_connections: 300
```
I fix templates/cluster.yaml local with:

```
postgresql:
    shared_preload_libraries:
      {{- if eq .Values.type "timescaledb" }}
      - timescaledb
      {{- end }}
      {{- with .Values.cluster.postgresql.shared_preload_libraries }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
    {{- with .Values.cluster.postgresql.parameters }}
    parameters:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.cluster.postgresql.pg_hba }}
    pg_hba:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.cluster.postgresql.pg_ident }}
    pg_ident:
      {{- toYaml . | nindent 6 }}
    {{- end }}
```
This fix solved duplicate key postgresql.parameters.parameters.
Please fix this bug.

Thanks.
