### ISSUE TITLE
Wrong PGDATA directory for official TimescaleDB image: allow customizing PGDATA?

### ISSUE THREAD

**Issue by Felk** [cloudnative-pg/charts#414]
I'm trying to get the "stock" TimescaleDB docker image working with cnpg. This is the Cluster definition I'm using:

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: my-timeseries-db
spec:
  instances: 1
  # cnpg needs to know the pg major version. because the timescale image tags don't follow an auto-detectable pattern,
  # we specify the major pg version manually using an image catalog.
  # See https://github.com/cloudnative-pg/cloudnative-pg/blob/main/docs/src/container_images.md#image-tag-requirements
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: timescale
    major: 16
  storage:
    size: 10Gi
  bootstrap:
    initdb:
      database: my_timeseries
      owner: my_timeseries
      secret:
        name: my-timeseries-credentials
```
with this cluster catalog:
```
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: timescale
spec:
  images:
    - major: 16
      image: timescale/timescaledb-ha:pg16
```

Unfortunately, the initdb container runs into the following issue:

```
{"level":"error","ts":"2024-10-07T09:10:41Z","msg":"Error while checking for an existing PGData","logging_pod":"wams-timeseries-db-1-initdb","error":"stat /var/lib/postgresql/data/pgdata: permission denied","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:125\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:163\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.InitInfo.CheckTargetDataDirectory\n\tpkg/management/postgres/initdb.go:141\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/initdb.initSubCommand\n\tinternal/cmd/manager/instance/initdb/cmd.go:151\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/initdb.NewCmd.func2\n\tinternal/cmd/manager/instance/initdb/cmd.go:108\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041\nmain.main\n\tcmd/manager/main.go:66\nruntime.main\n\t/opt/hostedtoolcache/go/1.22.6/x64/src/runtime/proc.go:271"}
Error: while verifying is PGDATA exists: stat /var/lib/postgresql/data/pgdata: permission denied
```

My suspicion is that this is due to timescaledb diverting from the defaults quite a bit, e.g. customizing `PGDATA`: https://github.com/timescale/timescaledb-docker-ha/blob/v1.9.5/Dockerfile#L432

Sadly this cannot be worked around by setting the `PGDATA` environment variable manually, because this...
```
  env:
  - name: PGDATA
    value: /home/postgres/pgdata/data
```
results in this error:
```
admission webhook "vcluster.cnpg.io" denied the request: Cluster.cluster.cnpg.io "wams-timeseries-db" is invalid: spec.postgresql.env[0].name: Invalid value: "PGDATA": the usage of this environment variable is reserved for the operator
```

Do you think it makes sense working towards getting this image to work? Or are non-cnpg-images strictly out of scope and I'd need to always use custom images like https://github.com/clevyr/docker-cloudnativepg-timescale ?

**Comment by itay-grudev** [comment]
@Felk The problem here is likely not with customizing the PGDATA directory but with permissions. The Official Timescale uses non-default `UID` and `GID`.

There are a bunch of small things you need to to to get the official Timescale image to work. I would recommend trying the [`cluster`](https://github.com/cloudnative-pg/charts/tree/main/charts/cluster) chart with `type: timescaledb` which will configure everything.

Alternatively override the `UID` and `GID` to `1000`.

**Comment by itay-grudev** [comment]
The cluster chart has a test suite, which you can look at for more advanced configuration.

Example:
https://github.com/cloudnative-pg/charts/blob/main/charts/cluster/test/timescale-minio-backup-restore/07-recovery_backup_pitr_cluster.yaml

**Comment by Felk** [comment]
That looks very promising, thank you!

I've tried using the Cluster helm chart using your linked examples plus the chart's Values.yaml for reference. I just can't quite get it to work, as it keeps telling me:

> Helm install failed for release timeseries-db/cloudnative-postgres with chart cluster@0.0.11: execution error at (cluster/templates/cluster.yaml:16:16): You need to provide your own cluster.imageName as an official timescaledb image doesn't exist yet.

I've tried the following yaml:
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: timeseries-db-hr
spec:
  releaseName: cloudnative-postgres
  chart:
    spec:
      chart: cluster
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
      version: "0.0.11"
  interval: 1h0m0s
  values:
    type: timescaledb
    mode: standalone
#Error is the same, whether these versions are specified or not
#    version:
#      postgresql: "15.7"
#      timescaledb: "2.15"
    cluster:
      instances: 1
      storage:
        size: 100Gi
#Error is the same, even if I explicitly reference the TimescaleDB docker image 'timescale/timescaledb-h2:pg15' via catalog
#      imageCatalogRef:
#        apiGroup: postgresql.cnpg.io
#        kind: ClusterImageCatalog
#        name: timescale
#        major: 15
    backups:
      enabled: false
```

If I try to specify `cluster.imageName` directly, I get this error:

> spec.imageName: Invalid value: "timescale/timescaledb-ha:pg15": invalid version tag

Given you linked actual test suite configs, I surely must have misunderstood some core concept and am doing something wrong, apologies for that. It would be really appreciated if you could point me in the right direction.

**Comment by itay-grudev** [comment]
I think this is on `main`, but haven't been released yet. You can try using the chart from `git` or you can give me some time to release all the changes. I'll try to do that today.

**Comment by Felk** [comment]
No problem, thanks for taking the time! In other news, setting the GID and UID seems to have worked :) Though maybe I'll encounter more issues down the line due to "bunch of small things you need to get for the official Timescale image to work" you mentioned that I'm ignoring right now

**Comment by itay-grudev** [comment]
I think the most important bit is that we pre-install the extension by default in the `app` database in the initdb step. You can achieve that by setting the following in your `Cluster`:

```yaml
bootstrap:
  initdb:
    postInitApplicationSQL:
      - CREATE EXTENSION IF NOT EXISTS timescaledb;
```

**Comment by wibed** [comment]
please reopen.

 event though all the data seems to be correct, i am unable to not have to run 
`CREATE EXTENSION IF NOT EXISTS timescaledb;` manually.

i have checked and it seems the configuration result in the correct output.
here is the configuration and the output.

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg-system

helmGlobals:
  chartHome: ../../../../base/cnpg

helmCharts:
  - name: cluster
    releaseName: lima-rancher-desktop
    includeCRDs: true
    valuesInline:
      namespaceOverride: cnpg-system
      type: timescaledb
      mode: standalone
      version:
        major: "16"
        timescaledb: "2.17"
      cluster:
        instances: 1
        #postgresGID: 65534
        #postgresUID: 65534
        postgresql:
          parameters:
            max_connections: "200"
            shared_buffers: "1GB"
            huge_pages: "off"
        storage:
          size: 1Gi
          storageClass: "local-path"
        monitoring:
          enablePodMonitor: false
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "1"
            memory: 1Gi

    repo: https://cloudnative-pg.github.io/charts

# output
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/instance: lima-rancher-desktop
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cluster
    app.kubernetes.io/part-of: cloudnative-pg
    helm.sh/chart: cluster-0.1.3
  name: lima-rancher-desktop-cluster
  namespace: cnpg-system
spec:
  affinity:
    topologyKey: topology.kubernetes.io/zone
  bootstrap:
    initdb:
      postInitApplicationSQL:
      - CREATE EXTENSION IF NOT EXISTS timescaledb;
  enablePDB: true
  enableSuperuserAccess: true
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    major: 16
    name: lima-rancher-desktop-cluster-timescaledb-ha
  imagePullPolicy: IfNotPresent
  instances: 1
  logLevel: info
  monitoring:
    disableDefaultQueries: false
    enablePodMonitor: false
  postgresGID: 1000
  postgresUID: 1000
  postgresql:
    parameters:
      huge_pages: "off"
      max_connections: "200"
      shared_buffers: 1GB
    shared_preload_libraries:
    - timescaledb
  primaryUpdateMethod: switchover
  primaryUpdateStrategy: unsupervised
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: "1"
      memory: 1Gi
  storage:
    size: 1Gi
    storageClass: local-path
---
```

**Comment by Felk** [comment]
Your config looks fine to me. fwiw and for reference, this is my working config:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: timescale
  namespace: cloudnative-postgres
spec:
  images:
    - major: 16
      image: timescale/timescaledb-ha:pg16
    - major: 17
      image: timescale/timescaledb-ha:pg17
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: my-timeseries-db
  namespace: my-timeseries-db
spec:
  instances: 1
  # cnpg needs to know the pg major version. because the timescale image tags don't follow an auto-detectable pattern,
  # we specify the major pg version manually using an image catalog.
  # See https://github.com/cloudnative-pg/cloudnative-pg/blob/main/docs/src/container_images.md#image-tag-requirements
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: timescale
    major: 17
  storage:
    size: 100Gi
  postgresql:
    shared_preload_libraries:
      - timescaledb
  # the timescaledb image uses a non-default user and group, see also https://github.com/cloudnative-pg/charts/issues/414
  postgresUID: 1000
  postgresGID: 1000

  bootstrap:
    initdb:
      postInitTemplateSQL:
        - CREATE EXTENSION IF NOT EXISTS timescaledb;
        - CREATE EXTENSION IF NOT EXISTS timescaledb_toolkit;
      database: my_timeseries
      owner: my_timeseries
      secret:
        name: my-timeseries-credentials
```
