### ISSUE TITLE
ArgoCD is forever stuck on updating the Cluster resource generated by the cluster chart

### ISSUE THREAD

**Issue by spantaleev** [cloudnative-pg/charts#426]
I'm using the following ArgoCD application:

```yml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg-cluster-something-postgres
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: something
    name: in-cluster
  source:
    repoURL: 'https://cloudnative-pg.io/charts/'
    targetRevision: 0.1.0
    helm:
      values: |
        fullnameOverride: cluster-postgres

        version:
          postgresql: "17"

        cluster:
          instances: 3

          storage:
            size: 3Gi

          initdb:
            database: something
            owner: something

          enableSuperuserAccess: true
          superuserSecret: cluster-postgres-superuser

          walStorage:
            enabled: true
    chart: cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources: []
  project: common
```

This generates a `Cluster` resource with `pg_hba: []` and `pg_ident: []`:

```yml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/instance: cloudnative-pg-cluster-something-postgres
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cluster
    app.kubernetes.io/part-of: cloudnative-pg
    argocd.argoproj.io/instance: cloudnative-pg-cluster-something-postgres
    helm.sh/chart: cluster-0.1.0
  name: cluster-postgres
  namespace: something
spec:
  affinity:
    topologyKey: topology.kubernetes.io/zone
  bootstrap:
    initdb:
      database: something
      owner: something
      postInitApplicationSQL: null
  enableSuperuserAccess: true
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  imagePullPolicy: IfNotPresent
  instances: 3
  logLevel: info
  managed: null
  monitoring:
    disableDefaultQueries: false
    enablePodMonitor: true
  postgresGID: 26
  postgresUID: 26
  postgresql:
    parameters: {}
    pg_hba: []
    pg_ident: []
    shared_preload_libraries: null
  primaryUpdateMethod: switchover
  primaryUpdateStrategy: unsupervised
  priorityClassName: null
  storage:
    size: 3Gi
    storageClass: null
  superuserSecret:
    name: cluster-postgres-superuser
  walStorage:
    size: 1Gi
    storageClass: null
```

ArgoCD continuously retries updating this `Cluster` resource, but the final result lacks the `pg_hba` and `pg_ident` keys. I suspect it's because they are empty lists.

Perhaps the code here could benefit from some `if` statements that exclude `pg_hba` and `pg_ident` if they would end up being empty?

https://github.com/cloudnative-pg/charts/blob/3c5dd5d9997592aeb1391b4d11ed2284d68dba31/charts/cluster/templates/cluster.yaml#L63-L66

This only became an issue with version 0.1.0 of the cluster chart. Downgrading to 0.0.11 (which [does not have](https://github.com/cloudnative-pg/charts/blob/b0b08c535265181018ed8aee6ee8f4bb5ac05cf0/charts/cluster/templates/cluster.yaml#L54-L62) these `pg_hba` and `pg_ident` keys) fixes the problem.

Seems like `pg_hba` got introduced in https://github.com/cloudnative-pg/charts/pull/321 while `pg_ident` got introduced in https://github.com/cloudnative-pg/charts/pull/377

**Comment by itay-grudev** [comment]
We can wrap them in a `with` statement so they are not included.

**Comment by pschichtel** [comment]
I'm also seeing this with a bunch of other entries:

![Image](https://github.com/user-attachments/assets/c6be9c58-3942-43b6-8b06-8f307d1cc596)

I'm using server-side apply

**Comment by logan-broit** [comment]
We also are running into this issue when using `v0.1.0` with fleet, as a workaround we put in values so `pg_hba` and `pg_ident` are not empty arrays and that seems to have resolved it for now...

Added this to our `values.yaml` for our cnpg clusters
```
    postgresql:
      pg_hba:
        - host all all 10.0.0.0/8 trust
      pg_ident:
        - postgres   local   postgres
```
