### ISSUE TITLE
No way to set `s3Credentials` to inheritFromIAMRole via cluster chart

### ISSUE THREAD

**Issue by cloudymax** [cloudnative-pg/charts#487]
When using S3 for barmanObjectStore backups, only secret credentials may be templated. An option to configure `inheritFromIAMRole` is not exposed

I would like to be able to reproduce the following via the helm chart:

```yaml
  backup:
    barmanObjectStore:
    # For backup, we S3 bucket to store data.
    # On this Blueprint, we create an S3 check the terraform output for it.
      destinationPath: s3://<your-s3-barman-bucket> #2
      s3Credentials:
        inheritFromIAMRole: true
```
