### ISSUE TITLE
Charts cloudnative-pg 0.23.0 crashing on CNPG version <1.25.0

### ISSUE THREAD

**Issue by saifulmuhajir** [cloudnative-pg/charts#500]
I was trying to upgrade our CNPG clusters to v1.24.2 where [a bug for switchover was fixed](https://github.com/cloudnative-pg/cloudnative-pg/issues/4821). Unfortunately, upgrading cloudnative-pg charts to 0.23.0 failed with `CrashLoopBackOff`. After some debugging, I found out the 0.23.0 version has `--max-concurrent-reconciles=10` while such feature doesn't exist in CNPG <1.25.0.

```
 spec:
   containers:
   - args:
     - controller
     - --leader-elect
     - --max-concurrent-reconciles=10
```

Will it be okay for me to just stay with charts 0.22.1 while upgrading CNPG to 1.24.2? And should you plan to "fix" the above?

Thanks.
