### ISSUE TITLE
Unable to restore from local backup by backupName

### ISSUE THREAD

**Issue by nobleess** [cloudnative-pg/charts#530]
I get this error
Error: execution error at (cluster/templates/cluster.yaml:132:5): You need to specify S3 region if endpointURL is not specified.
helm.go:86: 2025-03-08 18:51:19.153483 +0300 MSK m=+0.210108334 [debug] execution error at (cluster/templates/cluster.yaml:132:5): You need to specify S3 region if endpointURL is not specified.

version cluster chart 0.2.1
values.yaml
```
type: postgresql
mode: recovery

recovery:
  method: backup
  backupName: "database-clustermarket-database-daily-backup-1683244800"

cluster:
  instances: 1
```

PR
https://github.com/cloudnative-pg/charts/pull/529

**Comment by atimofeev** [comment]
I get the same error following [this official example](https://github.com/cloudnative-pg/charts/blob/0d95029eaeeac3c4a24fb4a11df4e1f04fa7a1f5/charts/cluster/examples/recovery-backup.yaml).

```yaml
---
mode: recovery

cluster:
  instances: 3
  storage:
    size: 25Gi
  walStorage:
    enabled: true
    size: 5Gi

recovery:
  method: backup
  backupName: xxx-postgresql-cluster-daily-backup-20250430000000

backups:
  enabled: true
  endpointURL: "xxx" # censored, using actually functional endpoint
  provider: s3
  s3:
    bucket: xxx-postgresql-backup
  secret:
    create: false
    name: xxx-postgresql-minio-creds
  wal:
    encryption: ""
  data:
    encryption: ""
```
