### ISSUE TITLE
Cluster Chart: Not possible to recover a specific database & owner for type object_store & backup

### ISSUE THREAD

**Issue by fpfuetsch** [cloudnative-pg/charts#557]
With the current values it is not possible to configure the properties `spec.bootstrap.recovery.database` and `spec.bootstrap.recovery.owner` of a `Cluster` when using `recovery.method: object_store` or  `recovery.method: backup` - check [here](https://github.com/cloudnative-pg/charts/blob/main/charts/cluster/templates/_bootstrap.tpl#L84-L94), while this is possible when using `recovery.method: pg_basebackup` - check [here](https://github.com/cloudnative-pg/charts/blob/main/charts/cluster/templates/_bootstrap.tpl#L34-L39). 

This makes it currently impossible to restore a certain database and owner from such backups to the `[cluster]-app` secret which instead contains credentials for the default `app` db and `app` owner as described [here](https://github.com/cloudnative-pg/cloudnative-pg/pull/2957).

In general, I would suggest that the values for `recovery` should contain a subkey to configure each `recovery.method`separately, as is already the case for the `pg_basebackup` method:

```yaml
recovery:
  method: object_store
  objectStore:
    provider: ...
    ...
  backup:
    name: ...
    ...
  pgBaseBackup:
    database: ...
    ...
```
