### ISSUE TITLE
Bypassing 'annotation too long' issue on CRD and Configmap

### ISSUE THREAD

**Issue by thomaspetit** [cloudnative-pg/charts#566]
Hi all,

Just quickly sharing a way to fix the `[annotation too long](metadata.annotations: Too long: must have at most 262144 bytes)` problems you might occur when applying the chart with eg ArgoCD.

Here are some topics that we're mentioning the issue:

- https://github.com/cloudnative-pg/charts/issues/280#issuecomment-2127739081
- https://github.com/cloudnative-pg/charts/pull/355

Kustomize to the rescue (combined with the Helm chart oc):
```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: []

namespace: cloudnative-pg

helmCharts:
  - name: cloudnative-pg
    includeCRDs: true
    valuesInline:
      monitoring:
        podMonitorEnabled: false
        grafanaDashboard:
          create: true
          annotations:
            argocd.argoproj.io/sync-options: ServerSideApply=true
    releaseName: cloudnative-pg
    version: 0.23.2
    repo: https://cloudnative-pg.github.io/charts

patches:
  - target:
      kind: CustomResourceDefinition
    patch: |
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: unspecified
        annotations:
          argocd.argoproj.io/sync-options: ServerSideApply=true

```

I realize that for some it's not ideal but you can elegantly fix it using 'kustomized helm' which ArgoCD also supports! Do note that you need to do a `--enable-helm` on your kustmize.
