### ISSUE TITLE
JSON schema validation fails for empty ("") backup encryption values

### ISSUE THREAD

**Issue by kuhnroyal** [cloudnative-pg/charts#572]
In the `_backup.tpl` empty strings passed for the encryption are converted to `null` which is not allowed by the JSON schema.

```
backup:
  barmanObjectStore:
    wal:
      encryption: {{ .Values.backups.wal.encryption }}
    data:
      encryption: {{ .Values.backups.data.encryption }}
```

But empty strings are considered valid according to docs:
```
One of `` (use the storage container default), `AES256` or `aws:kms`.
```

So maybe this can be force quoted?

```
backup:
  barmanObjectStore:
    wal:
      encryption: {{ .Values.backups.wal.encryption | quote }}
    data:
      encryption: {{ .Values.backups.data.encryption | quote }}
```
