### ISSUE TITLE
How to recover from latest available backup?

### ISSUE THREAD

**Issue by atimofeev** [cloudnative-pg/charts#582]
I've tried to re-deploy the cluster with these values:
```yaml
---
version:
  postgresql: "14"

mode: recovery

cluster:
  monitoring:
    enabled: true
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
  instances: 3
  storage:
    size: 25Gi
  walStorage:
    enabled: true
    size: 5Gi

recovery:
  method: backup
  backupName: daily-backup

backups:
  enabled: true
  retentionPolicy: "3d"
  endpointURL: "xxx"
  provider: s3
  s3:
    bucket: xxx-postgresql-backup
  secret:
    create: false
    name: xxx-postgresql-minio-creds
  wal:
    encryption: ""
  data:
    encryption: ""
  scheduledBackups:
    - name: daily-backup
      schedule: "0 0 0 * * *"
      backupOwnerReference: self
      method: barmanObjectStore
```

But this ends up in error, stating that `daily-backup` is not found, expecting it to match the full actual name, which is `xxx-postgresql-cluster-daily-backup-20250507000000`

What is the proper way of recovering from the latest backup?
