### ISSUE TITLE
Need to hardcode version helm chart cnpg operator in Cluster helm chart

### ISSUE THREAD

**Issue by nobleess** [cloudnative-pg/charts#590]
This will help to determine the current specification of the CRDs
Chart.yaml
```
apiVersion: v2
description: Deploys and manages a CloudNativePG cluster and its associated resources.
home: https://cloudnative-pg.io
icon: https://raw.githubusercontent.com/cloudnative-pg/artwork/main/cloudnativepg-logo.svg
keywords:
- postgresql
- postgres
- database
maintainers:
- email: itay+cloudnativepg-charts+github.com@grudev.com
  name: itay-grudev
name: cluster
--- new
dependencies:
- name: cloudnative-pg
  repository: "https://cloudnative-pg.github.io/charts/operator"
  version: z.y.*
---
sources:
- https://github.com/cloudnative-pg/charts
type: application
version: 0.3.0
```

This should help the user navigate dependencies more easily and make it easier to use.
