### ISSUE TITLE
Add ref to secret for update password in recovery

### ISSUE THREAD

**Issue by nobleess** [cloudnative-pg/charts#596]
I cant add ref to secret in recovery
https://cloudnative-pg.io/documentation/1.23/recovery/
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
[...]
spec:
  bootstrap:
    recovery:
      database: app
      owner: app
--- don't support ---
      secret:
        name: app-secret
--- ---
```
