### ISSUE TITLE
Secret not create for recovery methods  'import'

### ISSUE THREAD

**Issue by MishelSirotkin** [cloudnative-pg/charts#599]
Used last chart version 

In the values.yaml
```yaml
import:
      source:
      host: ""
      port: 5432
      username: ""
      database: ""
      sslMode: "verify-full"
      passwordSecret:
        # -- Whether to create a secret for the password
        create: false
        # -- Name of the secret containing the password
        name: ""
        # -- The key in the secret containing the password
        key: "password"
        # -- The password value to use when creating the secret
```
Secret not creating. 
template for it creating not found too.
