### ISSUE TITLE
Path to the Backup being created

### ISSUE THREAD

**Issue by svetashlegel** [cloudnative-pg/charts#600]
Used last chart version

In the values.yaml

```yaml
backups:
  enabled: true
  endpointCA:
    create: false
    name: ""
    key: ""
    value: ""
  destinationPath: "s3://<bucket>/"
  provider: s3
  s3:
    region: ""
    bucket: "<bucket>"
    path: "/"
    accessKey: ""
    secretKey: ""
  secret:
    create: true
    name: ""
  wal:
    compression: gzip
    maxParallel: 1
  data:
    compression: gzip
    jobs: 2

recovery:
  method: backup
  pitrTarget:
    time: ""
  backupName: "<backup-name>" 
  clusterName: ""
  database: app
  owner: ""
  endpointURL: ""
  endpointCA:
    create: false
    name: ""
    key: ""
    value: ""
  destinationPath: "s3://<bucket>/"
  provider: s3
  s3:
    region: ""
    bucket: "<bucket>"
    path: "/"
    accessKey: ""
    secretKey: ""
```

The backup is created along the path: `s3://<bucket>/<backup-name>/`
But when restoring it tries to find in: `s3://<bucket>/<namespace>/<backup-name>/`
I can't find where the namespace name is added/removed to the path.
