### ISSUE TITLE
Restore from snapshot followed by WAL replay to the latest cluster state

### ISSUE THREAD

**Issue by MishelSirotkin** [cloudnative-pg/charts#604]
Try to restore cluster from shapshot.
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-restore
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  # Persistent storage configuration
  storage:
    storageClass: sc-stage-topolvm
    size: 3Gi
  
  bootstrap:
    recovery:
      source: origin
      volumeSnapshots:
        storage:
          name: mishel-cluster-1-20250602-110259
          kind: VolumeSnapshot
          apiGroup: snapshot.storage.k8s.io
  

  externalClusters:
    - name: origin 
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: mishel-cluster-backup
          serverName: mishel-cluster
```

If not define source: origin and externalClusters: - all ok - cluster has been restored. But if it definded recived  
```
Status:
  Conditions:
    Last Transition Time:  2025-06-02T14:35:50Z
    Message:               Cluster Is Not Ready
    Reason:                ClusterIsNotReady
    Status:                False
    Type:                  Ready
  Phase:                   Cluster cannot proceed to reconciliation due to an unknown plugin being required
  Phase Reason:            Unknown plugin: 'barman-cloud.cloudnative-pg.io'. This may be caused by the plugin not being loaded correctly by the operator. Check the operator and plugin logs for errors
```
Which plugin needs to be specified in the manifest?
