### ISSUE TITLE
Barman setup for S3 using chart and inherited role

### ISSUE THREAD

**Issue by kensentor** [cloudnative-pg/charts#611]
I'm uncertain whether I've found an issue regarding Barman and the cluster Helm chart. In short, I have a AWS EKS cluster, built with the chart, with Barman scheduled backups that are not running due to an IAM error that suggests that Barman is attempting to assume its service account via the instance manager's service account and failing due to a lack of IAM permissions. I don't see how I can increase those instance manager permissions, though, and am unsure if this is a problem with the chart, Barman, or my own setup.

Chart version: cluster-0.3.1

More descriptively:

I have an EKS cluster called `cluster-example`, built in AWS EKS with the Python CDK. When Barman tries to run a scheduled backup, it gives this backtrace:

```{"level":"info","ts":"2025-06-12T20:49:49.961858935Z","logger":"barman-cloud-check-wal-archive","msg":"2025-06-12 20:49:49,961 [7322] WARNING: Refreshing temporary credentials failed during mandatory refresh period.","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2025-06-12T20:49:49.961882199Z","logger":"barman-cloud-check-wal-archive","msg":"Traceback (most recent call last):","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2025-06-12T20:49:49.961885074Z","logger":"barman-cloud-check-wal-archive","msg":"  File \"/usr/local/lib/python3.11/dist-packages/botocore/credentials.py\", line 567, in _protected_refresh","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2025-06-12T20:49:49.961894263Z","logger":"barman-cloud-check-wal-archive","msg":"    metadata = self._refresh_using()","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2025-06-12T20:49:49.961898617Z","logger":"barman-cloud-check-wal-archive","msg":"               ^^^^^^^^^^^^^^^^^^^^^","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2025-06-12T20:49:49.961900824Z","logger":"barman-cloud-check-wal-archive","msg":"  File \"/usr/local/lib/python3.11/dist-packages/botocore/credentials.py\", line 716, in fetch_credentials","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2025-06-12T20:49:49.961905306Z","logger":"barman-cloud-check-wal-archive","msg":"    return self._get_cached_credentials()","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2025-06-12T20:49:49.961911067Z","logger":"barman-cloud-check-wal-archive","msg":"           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2025-06-12T20:49:49.961915374Z","logger":"barman-cloud-check-wal-archive","msg":"  File \"/usr/local/lib/python3.11/dist-packages/botocore/credentials.py\", line 726, in _get_cached_credentials","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2025-06-12T20:49:49.961919917Z","logger":"barman-cloud-check-wal-archive","msg":"    response = self._get_credentials()","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2025-06-12T20:49:49.96192435Z","logger":"barman-cloud-check-wal-archive","msg":"               ^^^^^^^^^^^^^^^^^^^^^^^","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2025-06-12T20:49:49.961928677Z","logger":"barman-cloud-check-wal-archive","msg":"  File \"/usr/local/lib/python3.11/dist-packages/botocore/credentials.py\", line 974, in _get_credentials","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2025-06-12T20:49:49.961931252Z","logger":"barman-cloud-check-wal-archive","msg":"    response = client.assume_role_with_web_identity(**kwargs)","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2025-06-12T20:49:49.961933444Z","logger":"barman-cloud-check-wal-archive","msg":"               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2025-06-12T20:49:49.961935791Z","logger":"barman-cloud-check-wal-archive","msg":"  File \"/usr/local/lib/python3.11/dist-packages/botocore/client.py\", line 595, in _api_call","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2025-06-12T20:49:49.961942723Z","logger":"barman-cloud-check-wal-archive","msg":"    return self._make_api_call(operation_name, kwargs)","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2025-06-12T20:49:49.961946952Z","logger":"barman-cloud-check-wal-archive","msg":"           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2025-06-12T20:49:49.961951187Z","logger":"barman-cloud-check-wal-archive","msg":"  File \"/usr/local/lib/python3.11/dist-packages/botocore/context.py\", line 123, in wrapper","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2025-06-12T20:49:49.961955544Z","logger":"barman-cloud-check-wal-archive","msg":"    return func(*args, **kwargs)","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2025-06-12T20:49:49.961959809Z","logger":"barman-cloud-check-wal-archive","msg":"           ^^^^^^^^^^^^^^^^^^^^^","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2025-06-12T20:49:49.961964028Z","logger":"barman-cloud-check-wal-archive","msg":"  File \"/usr/local/lib/python3.11/dist-packages/botocore/client.py\", line 1058, in _make_api_call","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2025-06-12T20:49:49.961967233Z","logger":"barman-cloud-check-wal-archive","msg":"    raise error_class(parsed_response, operation_name)","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2025-06-12T20:49:49.96196969Z","logger":"barman-cloud-check-wal-archive","msg":"botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRoleWithWebIdentity operation: Not authorized to perform sts:AssumeRoleWithWebIdentity","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2025-06-12T20:49:49.961975993Z","logger":"barman-cloud-check-wal-archive","msg":"2025-06-12 20:49:49,961 [7322] ERROR: Barman cloud WAL archive check exception: An error occurred (AccessDenied) when calling the AssumeRoleWithWebIdentity operation: Not authorized to perform sts:AssumeRoleWithWebIdentity","pipe":"stderr","logging_pod":"cluster-example-1"}
```

So, it's failing due to a lack of IAM Role permissions. Looking in CloudTrail, I see this error:

```json
{
    "eventVersion": "1.08",
    "userIdentity": {
        "type": "WebIdentityUser",
        "principalId": "arn:aws:iam::<redacted>:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/3D78823AC49E7479C015B44C248EC56F:sts.amazonaws.com:system:serviceaccount:default:cluster-example",
        "userName": "system:serviceaccount:default:cluster-example",
        "identityProvider": "arn:aws:iam::<redacted>:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/3D78823AC49E7479C015B44C248EC56F"
    },
    "eventTime": "2025-06-12T20:45:39Z",
    "eventSource": "sts.amazonaws.com",
    "eventName": "AssumeRoleWithWebIdentity",
    "awsRegion": "us-east-1",
    "sourceIPAddress": "<redacted>",
    "userAgent": "Boto3/1.38.25 md/Botocore#1.38.25 ua/2.1 os/linux#6.1.134-152.225.amzn2023.x86_64 md/arch#x86_64 lang/python#3.11.2 md/pyimpl#CPython m/Z,b cfg/retry-mode#legacy Botocore/1.38.25",
    "errorCode": "AccessDenied",
    "errorMessage": "An unknown error occurred",
    "requestParameters": {
        "roleArn": "arn:aws:iam::<redacted>:role/testbed-eks-CNPGClusterBarmanServiceA-j8uOlLmjFbp8",
        "roleSessionName": "botocore-session-1749761139"
    },
    "responseElements": null,
    "requestID": "70ebab19-bd4f-43d8-a12b-c4c52825bd32",
    "eventID": "2fd1cf45-5ae6-4eee-b7c6-898b90261b4d",
    "readOnly": true,
    "resources": [
        {
            "accountId": "<redacted>",
            "type": "AWS::IAM::Role",
            "ARN": "arn:aws:iam::<redacted>:role/testbed-eks-CNPGClusterBarmanServiceA-j8uOlLmjFbp8"
        }
    ],
    "eventType": "AwsApiCall",
    "managementEvent": true,
    "recipientAccountId": "<redacted>",
    "eventCategory": "Management",
    "tlsDetails": {
        "tlsVersion": "TLSv1.3",
        "cipherSuite": "TLS_AES_128_GCM_SHA256",
        "clientProvidedHostHeader": "sts.us-east-1.amazonaws.com"
    }
}
```

Based on `userIdentity` and `requestParameters`, this suggests that the instance manager's service account is trying to assume the service account role I specified in the Helm chart for Barman and is unable to due to a lack of permissions. However, I don't see where in the chart I could affect that. Here are the relevant bits from my `cluster.yaml`.

```yaml
spec:
  backup:
    barmanObjectStore:
      data:
        compression: gzip
        encryption: AES256
        jobs: 2
      destinationPath: s3://cnpg-backups-testbed-eks/
      endpointURL: https://s3.us-east-1.amazonaws.com
      s3Credentials:
        inheritFromIAMRole: true
      wal:
        compression: gzip
        encryption: AES256
        maxParallel: 1
    retentionPolicy: 7d
    target: prefer-standby
  bootstrap:
    initdb:
      database: app
      encoding: UTF8
      localeCType: C
      localeCollate: C
      owner: app
  enablePDB: true
  enableSuperuserAccess: true
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17
  imagePullPolicy: IfNotPresent
  instances: 1
  logLevel: info
  primaryUpdateMethod: switchover
  primaryUpdateStrategy: unsupervised
  replicationSlots:
    highAvailability:
      enabled: true
      slotPrefix: _cnpg_
    synchronizeReplicas:
      enabled: true
    updateInterval: 30
  resources: {}
  serviceAccountTemplate:
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::<redacted>:role/testbed-eks-CNPGClusterBarmanServiceA-38N6ziSYBu7r
```
