### ISSUE TITLE
Possibility to set watched namespaces in values.yaml

### ISSUE THREAD

**Issue by lusu007** [cloudnative-pg/charts#69]
Using the kubectl cnpg plugin it is possible to generate a `cnpg_for_specific_namespace.yaml`. It would be nice to be able to set the watched namespaces inside the `values.yaml` as well.

**Comment by Zeratoxx** [comment]
ping

**Comment by phisco** [comment]
That's already possible, by setting the following values:
```yaml
config:
  data:
    WATCH_NAMESPACE: namespace-a,namespace-b
```
Added a clear reference to all the available options there in #114 alongside a few other docs minor fixes.
