### ISSUE TITLE
Configure operator cm additional variables

### ISSUE THREAD

**Issue by edgarkz** [cloudnative-pg/charts#76]
I can't find in current helm chart any cm configuration, we have only an option to enable or disable config creation and config name

Can you please also add an option to pre-populate data section?

config:
  data: |
    INHERITED_ANNOTATIONS: test

Reference: https://cloudnative-pg.io/documentation/1.18/operator_conf/

**Comment by phisco** [comment]
Hi @edgarkz, that should already be working with the following configuration:
```
config:
  create: true
  data:
    INHERITED_ANNOTATIONS: test
```
Feel free to reopen the issue if that's not the case.
